version: '2'
services:
  web:
      image: nginx:latest
      ports:
          - "8888:80"
      volumes:
          - ./app:/var/www/html
          - ./site.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      image: bwinkers/docker-php7-phalcon
      volumes:
          - ./app:/var/www/html
      links:
          - db
  db:
     # version of mongo we'll use
    image: mongo:3.4

    # local port mapping to container port.  Remember, this
    # doesn't have to be 27017, you could make this availble
    # on port 3000 on our local machine via 3000:27017
    # if we really wanted to.
    ports:
      - 27017:27017

    # using a named volume
    volumes:
      - mongo:/data/db

    # OPTIONAL: This enforces the need for authentication
    command: mongod --auth

  logger:
      image: gliderlabs/logspout
      ports:
          - "8000:80"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock        
volumes:  
  mongo:          