version: '2'
services:
  web:
      image: nginx:latest
      ports:
          - "8888:80"
      volumes:
          - ./app:/var/www/html
          - ./site.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      image: bwinkers/docker-php7-phalcon
      volumes:
          - ./app:/var/www/html
  db:
      image: orientdb:2.2.20
      command: dserver.sh
      volumes:
#        - ./var/odb1/config:/orientdb/config
        - ./var/odb1/databases:/orientdb/databases
      environment:
        ORIENTDB_ROOT_PASSWORD: root
        ORIENTDB_NODE_NAME: odb1
      ports:
        - 2480:2480
        - 2424:2424
  logger:
      image: gliderlabs/logspout
      ports:
          - "8000:80"
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock        